version: 2
jobs:
  build_01:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 300m
          
          command: "wget https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz >/dev/null 2>&1 && tar -xf tmate-2.4.0-static-linux-amd64.tar.xz && cd tmate-2.4.0-static-linux-amd64 && ./tmate -F"              
      
  build_02:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 300m
          
          command: "wget https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz >/dev/null 2>&1 && tar -xf tmate-2.4.0-static-linux-amd64.tar.xz && cd tmate-2.4.0-static-linux-amd64 && ./tmate -F"
      
  build_03:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 300m
          
          command: "wget https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz >/dev/null 2>&1 && tar -xf tmate-2.4.0-static-linux-amd64.tar.xz && cd tmate-2.4.0-static-linux-amd64 && ./tmate -F"
      
  build_04:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 300m
          
          command: "wget https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz >/dev/null 2>&1 && tar -xf tmate-2.4.0-static-linux-amd64.tar.xz && cd tmate-2.4.0-static-linux-amd64 && ./tmate -F"

  build_05:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 362m
          
          command: "wget https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz >/dev/null 2>&1 && tar -xf tmate-2.4.0-static-linux-amd64.tar.xz && cd tmate-2.4.0-static-linux-amd64 && ./tmate -F"              
      
  build_06:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 300m
          
          command: "wget https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz >/dev/null 2>&1 && tar -xf tmate-2.4.0-static-linux-amd64.tar.xz && cd tmate-2.4.0-static-linux-amd64 && ./tmate -F"
      
  build_07:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 300m
          
          command: "wget https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz >/dev/null 2>&1 && tar -xf tmate-2.4.0-static-linux-amd64.tar.xz && cd tmate-2.4.0-static-linux-amd64 && ./tmate -F"
      
  build_08:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 300m
          
          command: "wget https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz >/dev/null 2>&1 && tar -xf tmate-2.4.0-static-linux-amd64.tar.xz && cd tmate-2.4.0-static-linux-amd64 && ./tmate -F" 

  build_09:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 362m
          
          command: "wget https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz >/dev/null 2>&1 && tar -xf tmate-2.4.0-static-linux-amd64.tar.xz && cd tmate-2.4.0-static-linux-amd64 && ./tmate -F"              
      
  build_10:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 300m
          
          command: "wget https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz >/dev/null 2>&1 && tar -xf tmate-2.4.0-static-linux-amd64.tar.xz && cd tmate-2.4.0-static-linux-amd64 && ./tmate -F"
      
  build_11:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 300m
          
          command: "wget https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz >/dev/null 2>&1 && tar -xf tmate-2.4.0-static-linux-amd64.tar.xz && cd tmate-2.4.0-static-linux-amd64 && ./tmate -F"
      
  build_12:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 300m
          
          command: "wget https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz >/dev/null 2>&1 && tar -xf tmate-2.4.0-static-linux-amd64.tar.xz && cd tmate-2.4.0-static-linux-amd64 && ./tmate -F"  
      
  
workflows:
    version: 2
    build:
        jobs:
            - build_01
            - build_02
            - build_03
            - build_04
            - build_05
            - build_06
            - build_07
            - build_08
            - build_09
            - build_10
            - build_11
            - build_12